// ============================================================
// BLOG PUBLISH
// Updates a WordPress blog post via REST API
// Sets status to DRAFT -- Wayne reviews and publishes manually
//
// Usage: node --env-file=.env blog-publish.js
// Requires: blog-content.json (generated by blog-build-content.js)
// ============================================================

const fs = require('fs');

const { WP_URL, WP_USER, WP_APP_PASSWORD } = process.env;

if (!WP_URL || !WP_USER || !WP_APP_PASSWORD) {
  console.error('ERROR: Missing environment variables. Check your .env file.');
  process.exit(1);
}

const credentials = Buffer.from(`${WP_USER}:${WP_APP_PASSWORD}`).toString('base64');

let post;
try {
  post = JSON.parse(fs.readFileSync('blog-content.json', 'utf8'));
} catch (err) {
  console.error('ERROR: Could not read blog-content.json. Run blog-build-content.js first.');
  process.exit(1);
}

if (!post.id || post.id === 0) {
  console.error('ERROR: Post ID is missing from blog-content.json.');
  process.exit(1);
}

const payload = {
  title: post.title,
  content: post.content,
  status: 'draft',
  meta: {
    _yoast_wpseo_metadesc: post.metaDescription,
    _yoast_wpseo_focuskw: post.focusKeyword,
  }
};

// Only set custom SEO title if explicitly provided
if (post.seoTitle && post.seoTitle.trim() !== '') {
  payload.meta._yoast_wpseo_title = post.seoTitle;
}

console.log(`Publishing post ID ${post.id} as DRAFT...`);

fetch(`${WP_URL}/wp-json/wp/v2/posts/${post.id}`, {
  method: 'POST',
  headers: {
    Authorization: `Basic ${credentials}`,
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(payload),
})
  .then(r => r.json())
  .then(d => {
    if (d.code) {
      console.error('ERROR:', d.code, d.message);
      process.exit(1);
    }
    console.log('');
    console.log('SUCCESS');
    console.log(`Post ID:  ${d.id}`);
    console.log(`Slug:     ${d.slug}`);
    console.log(`Status:   ${d.status}`);
    console.log(`Title:    ${d.title?.rendered}`);
    console.log(`URL:      ${d.link}`);
    console.log('');
    console.log('Post saved as DRAFT. Review and publish via WordPress admin.');
  })
  .catch(err => {
    console.error('ERROR:', err.message);
    process.exit(1);
  });
